export const PATH = {
  // Public Routes
  HOME: '/',

  // Foundation Routes
  FOUNDATION: '/foundation',
  FOUNDATION_ALERT: '/foundation/alert',
  FOUNDATION_BUTTON: '/foundation/button',
  FOUNDATION_CHECKBOX: '/foundation/checkbox',
  FOUNDATION_COLOR_PALLET: '/foundation/color-pallet',
  FOUNDATION_COLOR_PICKER: '/foundation/color-picker',
  FOUNDATION_DATE_PICKER: '/foundation/date-picker',
  FOUNDATION_DRAWER: '/foundation/drawer',
  FOUNDATION_FORM: '/foundation/form',
  FOUNDATION_IMAGE: '/foundation/image',
  FOUNDATION_INPUT: '/foundation/input',
  FOUNDATION_MESSAGE: '/foundation/message',
  FOUNDATION_MODAL: '/foundation/modal',
  FOUNDATION_RADIO: '/foundation/radio',
  FOUNDATION_SELECT: '/foundation/select',
  FOUNDATION_SWITCH: '/foundation/switch',
  FOUNDATION_TABLE: '/foundation/table',
  FOUNDATION_TAG: '/foundation/tag',
  FOUNDATION_TEXT: '/foundation/text',
  FOUNDATION_TIME_PICKER: '/foundation/time-picker',
  FOUNDATION_TITLE: '/foundation/title',
  FOUNDATION_TOOLTIP: '/foundation/tooltip',
  FOUNDATION_TRANSFER: '/foundation/transfer',

  // SAMPLES: '/samples',
  // FRONT_RECOGNITION_TEMP: '/front-recognition-temp',
  // CHECK_SHEET_TEMP: '/check-sheet-temp',
  // CREATE_CHECK_SHEET_TEMP: '/create-check-sheet-temp',
  // RECORD_TEMP: '/record-temp',
  // RECORD: '/record',
  // VIEWR_TEMP: '/viewer-temp',
  // WORK_PLAN_TEMP: '/work-plan-temp',

  // Private Routes
  // CHECK_SHEET: '/check-sheet',
  // CHECK_SHEET_NEW: '/check-sheet-new',
  // CREATE_CHECK_SHEET: '/create-check-sheet',
  // UPDATE_CHECK_SHEET: '/update-check-sheet',
  // WORK_PLAN: '/work-plan',
  // ESP32: '/esp32',
  // VIEWER: '/viewer',
  // FRONT_RECOGNITION: '/front-recognition',
};
